### ISSUE TITLE
PHP 7.4 cannot be supported

### ISSUE THREAD

**Issue by cweiske** [gwsn/flysystem-sharepoint-adapter#2]
composer.json says that PHP 7.4 is supported, but flysystem 3.0 already requires PHP 8:
https://github.com/thephpleague/flysystem/blob/3.0.0/composer.json

7.4 should thus be removed from composer.json

**Comment by jnovermars** [comment]
@cweiske you are right, could you be so kind to create a Pull Request for this

**Comment by jnovermars** [comment]
this is fixed in 1.1.0
