### ISSUE TITLE
Inconsistencies with local filesystem adapter

### ISSUE THREAD

**Issue by irealworlds** [gwsn/flysystem-sharepoint-adapter#6]
I've been using this package a little lately and I've notices that there are a few differences in behaviour between the results obtained with this package and results obtained when working with the local adapter.

For example, listing files and directories with this adapter returns only file names, while the local adapter returns full paths.
Another example is that calling `exists` with this adapter throws an exception for directories, while the local adapter allows this case.

In my opinion, these differences should be removed and behaviour should be as consistent as possible.
How do you (the maintainers) view these differences? I would be open to contributing to seeking out these differences and building a PR that removes them if you agree that they should be removed (this would be breaking change since behaviour would change in a lot of places potentially, so this should be part of a major release.)

**Comment by jnovermars** [comment]
Thanks for taking the time to react, it would be nice if both codebases acted the same, and i was under the impression they did because the flysystem adapter is just a wrapper around the SharePoint-SDK. I do not have a Sharepoint running directly so I cannot test the point you make directly. 

You are always free to make a PR with the suggested changes and indeed if we do that it should be a breaking change as it changes the behavior.

**Comment by pasloc** [comment]
The `exists` method throws an exception if the path is a folder. I had to create a workaround like this to do the check:

```php
$exists = false;
try {
    $exists = $disk->exists("audio_austausch/{$productNo}_audio");
} catch (\Throwable $e) {
    $exists = $e->getMessage() === 'Check for file exists but path is actually a folder';}
```

**Comment by jnovermars** [comment]
@pasloc the exists function is meant to be for files, so the exception is correct.

what you can do to check directories is as follow:
```
$adapter = Storage::disk('sharepoint')->getAdapter();
$adapter->directoryExists('/dummy');

// Or like in your case:
$exists = false;
try {
    $adapter = $disk->getAdapter();
    $exists = $adapter->directoryExists("audio_austausch/{$productNo}_audio");
} catch (\Throwable $e) {
    // handle other exceptions
}

```

**Comment by jnovermars** [comment]
Moved question of @pasloc to new issue #8
