### ISSUE TITLE
Uploading images to sharepoint

### ISSUE THREAD

**Issue by jaapgoorhuis** [gwsn/flysystem-sharepoint-adapter#7]
Hi, 

I try to upload images using your package but i get a corrupted image file.
Is there an option to do so?
I have tried the following:
 Storage::disk('sharepoint')->put('image.png', $this->image, 'public');

it uploads the file to my sharepoint but its a corrupted file.

Thanks in advandage

**Comment by jnovermars** [comment]
i cannot reproduce this locally:
What i did to reproduce is: 

1. Getting a clean Laravel environment
2. Put image in directory `storage/app` that is called `dummy.png`
3. Configured local filestorage and sharepoint filestorage in config
4. Then created a controller and put the following code in controller:

```
$image = Storage::disk('local')->get('dummy.png');
Storage::disk('sharepoint')->put('image.png', $image, 'public');
$image2 = Storage::disk('sharepoint')->get('image.png');

echo '<img src="data:image/png;base64,'.base64_encode($image2).'" />';
die();
```

**Comment by jnovermars** [comment]
@jaapgoorhuis can you use the code snippet with your image to isolate the issue?

**Comment by jaapgoorhuis** [comment]
Hi jnovermars.
Sorry for my late reaction.
Works great. Thanks! 
The issue was that i tried to store the image in sharepoint directly on upload. 
now i upload the image first to my server and then to sharepoint like u suggest.

Thanks again!

**Comment by jnovermars** [comment]
Hey Jaap,

no worries, glad that it is solved.
