### ISSUE TITLE
Bug with lastModified(string $path) on FlysystemSharepointAdapter

### ISSUE THREAD

**Issue by actengage** [gwsn/flysystem-sharepoint-adapter#9]
First off, thanks for the work implementing Sharepoint adapter. Your setup instructions saved us a lot of time integrating sharepoint to our Laravel application just making it easier to configure. Much appreciated!

I should probably submit a PR for this, but wanted to submit this issue before I submitted a PR in the name of laziness. 

I'm trying to get the lastModified timestamp of a file and to my surprise this code existed. However, your method declaration is wrong and is typed to return a `FileAttributes` type. The first issue is that `checkLastModified` method returns an `int`. Second, your method as declared below returns `void`. Not sure how exactly you want to fix this, but below is a possible solution.

Incorrect:

```php
    /**
     * @param string $path
     * @return FileAttributes
     * @throws \Exception
     */
    public function lastModified(string $path): FileAttributes
    {
        $this->connector->getFile()->checkFileLastModified($this->applyPrefix($path));
    }
```

Correct:

```php
    /**
     * @param string $path
     * @return int
     * @throws \Exception
     */
    public function lastModified(string $path): int
    {
        return $this->connector->getFile()->checkFileLastModified($this->applyPrefix($path));
    }
```

**Comment by jnovermars** [comment]
Thanks for the reporting the bug, it think you are right and I will try to reproduce it and fix it this week but if you have time feel free to open a pr

**Comment by jnovermars** [comment]
@actengage i merged your PR and will create new version for it

**Comment by actengage** [comment]
awesome. thanks a lot. ive been using my fork in production for a week or so and everything works as far as I can tell.

**Comment by jnovermars** [comment]
you can use Version v1.1.1 from now on then ;)
